### PR TITLE
Modified values on some parameters on soft-coding xml-s

### PR DESCRIPTION
**Pull request by Porrumentzio**
Sorry for the previous PR to master, I already closed it

### CODE REVIEW

**Comment by Porrumentzio** [comment]
If this works, what remains is to renew the flag (if possible). Also I would like to try the apk with the changes made, but although I get no errors with ./gradle, I don't find the apk.

**Comment by nicoursi** [comment]
please rebase again because i pushed a commit

**Comment by nicoursi** [comment]
`addons/languages/esperanto/apk/build/outputs/apk/debug`

Do you know you can search for a file? :) if you searched for `.apk` you would have found it

**Comment by nicoursi** [comment]
this PR is full of commits that have already beaing merged. Rebase, test, and  create a new branch if you need to apply more modifications

**Comment by nicoursi** [comment]
Did you find the apk?

**Comment by Porrumentzio** [comment]
Yes, thanks. It works as expected!
I added more commits, and thanks for the layout-width rework. By the way, does it not work putting the keyWidth param into Row?
> <Row android:keyWidth="9%p"\>

**Comment by nicoursi** [comment]
That works if you want all the keys of the same size, but in that case you had two bigger keys: `shift` and `back space` that are biggeer than 9

**Comment by Porrumentzio** [comment]
That's right. What I did was to add the parameter to those two keys, as exception. That would work, right?

**Comment by nicoursi** [comment]
It did not work. It was too many keys and it worked only by setting the size for the smaller keys

**Comment by Porrumentzio** [comment]
Okay, no matter so

**Pull request closed without merging**
