### PR TITLE
Added two more characters to legals on wordlist and clearer keyWidth on bepo

### PR DESCRIPTION
**Pull request by Porrumentzio**
I added ' and - as legal characters on ~/pack/build.gradle, because they're used in formal and poetic Esperanto sometimes.

In bepo:
* Left keyboard width to 9.09
* Concreted bottom row width to 10

Despite that, now I'm not able to run ./gradle commands. I get this error:

> \* What went wrong:
> Execution failed for task ':addons:languages:esperanto:pack:makeDictionary'.
> \> java.lang.ArrayIndexOutOfBoundsException (no error message)

Could you take a look to it? It's about Java classes

### CODE REVIEW

**Comment by nicoursi** [comment]
Have you added more text files? Remember, no more that 30MB in total

**Comment by Porrumentzio** [comment]
No, I added nothing; there are just 29,9MB. Is it possible that the command is taking previous merged files as inputs?

**Comment by nicoursi** [comment]
Your code is failing too many tests, fix it. I do not want to see any red crosses ✗, only green   ✓

**Comment by nicoursi** [comment]
> No, I added nothing; there are just 29,9MB. Is it possible that the command is taking previous merged files as inputs?

Try, experiment, try again until you fix. This is how it works.I cannot do everything for you. Today i cannot compile any code.

**Comment by Porrumentzio** [comment]
I have trimmed a file until ./gradle worked. The .apk is good about layouts.
I had a problem with apostrophes `'`, because putting it into the legal characters rendered in the outputs as `&apos;`: #2451
I'm writing the script now.

A problem that I see is that, having almost all words with frequency of `1`, the words with higher freqs are displayed every time. These words are mostly taken from the prebuilts, which are websites.

**Comment by nicoursi** [comment]
>I have trimmed a file until ./gradle worked. The .apk is good about layouts.
I had a problem with apostrophes ', because putting it into the legal characters rendered in the outputs as &apos;: AnySoftKeyboard#2451
I'm writing the script now.

` &apos;` means `'` and it is supposed to be like that. Do not do anything to change it!

>A problem that I see is that, having almost all words with frequency of 1, the words with higher freqs are displayed every time. These words are mostly taken from the prebuilts, which are websites.

Yes, I know about that problem, I already talked about it in my last issue on the main repo. I already linked you with that issue.

We can change that with find/replace. Or you can write a script that handles that in a better way.

**Comment by nicoursi** [comment]
If Gradle is not working, it is because you are doing something wrong. Locate the exact error and fix it

**Comment by Porrumentzio** [comment]
I did nothing with `&apos;`.

I saw the issue you posted on the main repo about the freqs, yes! By find/replace method you mean searching for the amount of repetitions of each word and changing their freqs, into a scale of 1-250?
I don't have knowings to write a script to do that, but I'll research.

Now ./gradle works. I don't know why, but the space in disk of the inputs changed somewhen. The supposed space was 29,9MB, but in disk it was 30. Trimming lines from `eowiki_03.txt` resulted in a functioning ./gradle.

**Comment by nicoursi** [comment]
>By find/replace method you mean searching for the amount of repetitions of each word and changing their freqs, into a scale of 1-250?

Find/replace can be done manually with a text editor. The problem is that they are all 1. So, no much to change. If I'll have time I'll have a look at the `make-dictionary` plugin to see if iI can do something from there.

**Comment by nicoursi** [comment]
>By find/replace method you mean searching for the amount of repetitions of each word and changing their freqs, into a scale of 1-250?

Find/replace can be done manually with a text editor. The problem is that they are all 1. So, no much to change. If I'll have time I'll have a look at the `make-dictionary` plugin to see if iI can do something from there.
I don't have knowings to write a script to do that, but I'll research.

>Now ./gradle works. I don't know why, but the space in disk of the inputs changed somewhen. The supposed space was 29,9MB, but in disk it was 30. Trimming lines from eowiki_03.txt resulted in a functioning ./gradle.

**Comment by nicoursi** [comment]
ok, 

If you want to play with the make-dictionary plugin you have to modify these two files:
`buildSrc/src/main/java/GenerateWordsListTask.java`
`buildSrc/src/main/java/Parser.java`

It is possible, and not very hard. I just don't have the time for it. You are getting more indipendent now, so I can leave things to you.  Start with tweaking `maxFrequency` and then you can work your way up.

**Comment by Porrumentzio** [comment]
Thanks @nicoursi!
I already have made the script with Python and it works perfectly! It could be added to ASK or to its documentation, as it is very useful when extracting the wordlist from texts.

Tomorrow I'll have a look to makeDictionary

**Comment by Porrumentzio** [comment]
> `...:apk:assembleDebug`, it creates the dictionary from scratch again. Am I doing something wrong, for example should I use instead `inputs.xml`, or is it that way?

You are doing it wrong😂😂😂 you have to delete the `input` folder, and copy your stripped XML into `prebuilt` together with the other file that is already there.
It'll work. Save a copy of `inputs`just in case. Can I see your script?🙂

>about documentation

You can link your guide into `contributing.md` in the `addons` folder as further reference.

**Comment by Porrumentzio** [comment]
This was strange, as you edited my post and seems that I have answered myself 😅 
Before using `clean_words_merged.xml` in `prebuilts`, I would like to have the frequencies corrected.
I'll attach the script.

**_Documentation_**:
I have the files into local and nowhere to upload them to. How could I link them? Maybe creating a folder into the main project named `Documentation`?

________
It is not finished. It needs explanations and at least two new conditions (for Esperanto)
[clean_words_merged.py.txt](https://github.com/nicoursi/AnySoftKeyboard/files/5173730/clean_words_merged.py.txt)

**Comment by nicoursi** [comment]
> This was strange, as you edited my post and seems that I have answered myself 😅

I didn't even realize I did that 😂



You can improve "contributing.md" by adding information you think is missing by cherry picking from your guide

**Comment by Porrumentzio** [comment]
Hi @nicoursi, I have been trying to hack `buildSrc/src/main/java/GenerateWordsListTask.java` and `buildSrc/src/main/java/Parser.java` but I achieve nothing, as I find too little parameters to change.

Could you have a look to it when you have time?
With that and the script all would be finished

**Comment by Porrumentzio** [comment]
Hi again. I have been perfecting the script and now it's complete. As said above, what we/I need now is to have MakeDictionary plugin working well about frequencies, but I don't know how to do it.

Could you make it please?

**Pull request merged**
