### PR TITLE
Changed keyWidth parameter on eo_bepo.xml

### PR DESCRIPTION
**Pull request by Porrumentzio**
Maybe I didn't make well, as there were errors in the previous PR to `master`. So here's the new to `esperanto2`

### CODE REVIEW

**Comment by nicoursi** [comment]
Execution failed for task ':addons:languages:esperanto:apk:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /github/workspace/addons/languages/esperanto/pack/build/intermediates/packaged_res/debug/xml/eo_bepo.xml:3: AAPT: error: '9,09%p' is incompatible with attribute keyWidth (attr) dimension|fraction.

Fix that. 
If unit tests fail, you have to troubleshoot them.

**Comment by Porrumentzio** [comment]
I'll try with `9.09%p` and if not, I'll leave it on `9%p`

**Comment by nicoursi** [comment]
As you can compile and test, push only working code.

**Comment by nicoursi** [comment]
I pushed more code. every time I do that, you have to rebase:

do this when you are inside the branch, not in master!
`git pull --rebase upstream esperanto2`
then push again

**Comment by Porrumentzio** [comment]
Unfortunately I'm not able to compile, I still get errors that I don't know how to solve, as I thought I had all correct. But seems that isn't.

**Comment by nicoursi** [comment]
are you sure you are compiling with the right commands?

This will install it directly into your phone. If `adb devices" works, it will work the following command too.
./gradlew :addons:languages:esperanto:apk:installDebug

Otherwise do this
./gradlew :addons:languages:esperanto:apk:assembleDebug

you will find the apk into a subfolder of `build`, root forder (AnySofKeyboard)

**Comment by Porrumentzio** [comment]
With `assemble:Debug`:
irudia

And although the error with JDK appears there, I think I have it correctly configured in Android Studio:
irudia

**Comment by nicoursi** [comment]
`java --version`

**Comment by Porrumentzio** [comment]
> $ java --version
> Unrecognized option: --version
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
>

**Comment by nicoursi** [comment]
I pushed your commits, you can rebase and delete the last useless commit.
You do not have a working java environment. You should get something like this:

```
java --version
openjdk 11.0.8 2020-07-14 LTS
OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.41+23-CA (build 11.0.8+10-LTS, mixed mode)
```
Probably you have some conficts among different versions.

**Comment by nicoursi** [comment]
try with `java --v` or `java -v`

**Comment by nicoursi** [comment]
[esperanto_ASK.zip](https://github.com/nicoursi/AnySoftKeyboard/files/5150361/esperanto_ASK.zip)

Test it and see if it is ok. 

With wikipedia generated documents there is an issue. Read my last comment [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2447)

I added french and german diacritics to parse some French and German names. There is not much I can do, you either add foreign names into the dictionary or you'll get not existing split words.

There are a lot more characters in those wikipedia dumps, such as hungarian, czech and so on. I only included French and German. See what you want to do. 

Have a look here and see if there are words that do not exist in Esperanto.

[words_merged.zip](https://github.com/nicoursi/AnySoftKeyboard/files/5150392/words_merged.zip)

**Comment by Porrumentzio** [comment]
The other java commands didn't work. I have now putted java well, but I don't find `~/build` directory, only `buildSrc` and `build-logging`

I'm unable to execute the APKs, same as before: package seems broken.

About the issue with dictionary-making and haven seen the words_merged.xml, having foreign characters does not seem so problematic to me, but yes its consequence: having a lot of two-letter-words without any meaning due to their splitting.
It would be _possible_ to remove those *words* manually, but it's a gigantic labor.

**Comment by nicoursi** [comment]
>I'm unable to execute the APKs, same as before: package seems broken.

Did you unistall your current version of AnySoftwareKeyboard? Uninstall everything and install the debug versions. 

>About the issue with dictionary-making and haven seen the words_merged.xml, having foreign characters does not seem so problematic to me, but yes its consequence: having a lot of two-letter-words without any meaning due to their splitting.
It would be possible to remove those words manually, but it's a gigantic labor.

The solution I can see is adding all the diacritics belonging to other languages, so that instead of useless words you'll have names of famous people or places. So far I added French and German.

**Comment by nicoursi** [comment]
have you ever side loaded apks into your phone? are you sure the phone is authorized to do so?

**Comment by Porrumentzio** [comment]
I managed to install the APKs on other device, now I'm gonna work on improving them.

About words, I see two options:
1- Adding all possible diacritics and have proper names, among some not proper ones (kitchen from English as example)
2- Trying an script to remove words with foreign characters and then reviewing no-words

**Comment by nicoursi** [comment]
>The other java commands didn't work. I have now putted java well, but I don't find ~/build directory, only buildSrc and build-logging

The build folder will be created if ./gradle completes the building process without errors.

**Comment by Porrumentzio** [comment]
By the way, did you changed the names and descriptions on esperanto_keyboards.xml?

**Comment by nicoursi** [comment]
>About words, I see two options:
1- Adding all possible diacritics and have proper names, among some not proper ones (kitchen from English as example)

It does not work this way. If `kitchen` is in your wiki dumps, it will be included, no matter what. It does not contain any letters that do not belong to Esperanto. Different thing for `Dalì`. You either will have it or you'll have `Dal`

>2- Trying an script to remove words with foreign characters and then reviewing no-words

This would be the best option

**Comment by Porrumentzio** [comment]
So first would be to create the merged_words.xml with all the diacritics (and this way avoid broken words) and then create a script

**Comment by nicoursi** [comment]
>By the way, did you changed the names and descriptions on esperanto_keyboards.xml?

You are not allowed to use any language other than English. The name of the layout is always `esperanto`, and you can read the description in settings. 

Otherwise, if you have many languages, it will be difficult to find esperanto and or other languages

**Comment by nicoursi** [comment]
>So first would be to create the merged_words.xml with all the diacritics (and this way avoid broken words) and then create a script

This is the easiest solution

**Comment by nicoursi** [comment]
I am not sure the false space is working though. Try using it, if it does not work we'll remove it

**Comment by Porrumentzio** [comment]
"Eo" is the abbreviation of **E**sperant**o**. Having names such as "Eo QWERTY" or "Eo Dvorak" is much more easy to know which layout you are using.

Also, taking into account the idiosyncrasy of Esperanto, it's a reality that there are people who know Esperanto and not English. Taking this into account, isn't logic to have the Esperanto descriptions in such language?
______
False space is working well, yes! Try using a hashtag in Mastodon, Telegram, Twitter... and just after add the false space. You'll see the break of the hashtag!

**Comment by nicoursi** [comment]
>Also, taking into account the idiosyncrasy of Esperanto, it's a reality that there are people who know Esperanto and not English. Taking this into account, isn't logic to have the Esperanto descriptions in such language?

You have localization for that. If the phone locale is "en" it will be all in English. If the locale of the phone will be "eo" it will be all in eo, even ASK settings.

>"Eo" is the abbreviation of Esperanto. Having names such as "Eo QWERTY" or "Eo Dvorak" is much more easy to know which layout you are using.

I see what you mean. I'll change this one back

**Comment by Porrumentzio** [comment]
>But, although the phone being in Esperanto, the Esperanto package will remain all in English, right?

No, it will be localized. Try changing the locale of your phone and you'll see all the packages changing descriptions. I don't know if there are translations for eo yet, if not you can make them. I'll explain you how to, but never mix languages! You make the devs job harsh.

>What about having names such as "Eo Dvorak"?

I've already answered you about that ;)

**Comment by nicoursi** [comment]
To make translations for AnySoftwareKeyboard you need to use Crowdin. I think you can use the same login as github. Then translations will be automatically pushed into master regularly.

**Comment by Porrumentzio** [comment]
All understood now, I didn't know about localization of descriptions. Perfect so!

And no matter, I'll change the names by myself. I see you did not used `esperanto_pack_strings(_dont_translate).xml` and you entered the values rightly, without mentioning.
Is it preferable doing this?

**Comment by nicoursi** [comment]
do not forget to rebase BEFORE pushing

**Comment by Porrumentzio** [comment]
Sorry, I thought there were no changes

**Comment by nicoursi** [comment]
we're both working on it, so do it everytime before pushing.

I merged your commits before.

**Comment by Porrumentzio** [comment]
Okay, I'll be working. What will be working on?

**Comment by nicoursi** [comment]
> Okay, I'll be working. What will be working on?

When you push, I don't merge. I pull, I test, and I merge what works. After that, when you rebase, all the commits that have been merged will disappear, otherwise they'll stay there even if already merged.

Delete this commit, I don't even know what it is supposed to do:
`New commit. I had no success compiling.`

By the way, what country are you from?

**Comment by nicoursi** [comment]
I see you did not used `esperanto_pack_strings(_dont_translate).xml` and you entered the values rightly, without mentioning.
> Is it preferable doing this?
What do you mean by "I did not change"?

This is the file:
```
    <string name="esperanto_dictionary">Esperanto</string>
    <string name="eo_qwerty_keyboard">Esperanto</string>
    <string name="eo_qwertz_keyboard">Esperanto</string>
    <string name="eo_dvorak_keyboard">Esperanto</string>
    <string name="eo_azerty_keyboard">Esperanto</string>
    <string name="eo_bepo_keyboard">Esperanto</string>
    <string name="main_esperanto_keyboard_id">646ba9fd-8b22-48f9-a709-1af95d076e2b</string>
```

**Comment by Porrumentzio** [comment]
Okay, thanks for explaining the workflow. Really I'm only a translator, but although not being a developer, I think it's better to try and learn than wait that other people do what you want.

I'm from the [Basque Country](https://en.wikipedia.org/wiki/Basque_Country_(greater_region)). Where are you from?

**Comment by Porrumentzio** [comment]
About `esperanto_pack_strings_dont_translate.xml` and `esperanto_pack_strings.xml`:

They are files that have parameters mentioned in other files, instead of writing strings directly on those other files.

So having in `keyboards.xml` the value
> nameResId="@string/eo_qwerty_keyboard"

is same than having
> nameResId="Eo QWERTY"

[ when `@string/eo_qwerty_keyboard` on `esperanto_pack_strings_dont_translate.xml` has the value `Eo QWERTY`]

**Which is the preferd workflow of those two?**

**Comment by nicoursi** [comment]
>is same than having
>    nameResId="Eo QWERTY"

This is called hard coding. This way, automatic localization would not work. If you need to change the value of those strings, you can just modifying those files, otherwise to have to change all the code.

**Comment by Porrumentzio** [comment]
That was what I though. So I'll *soft code* ;)

**Comment by nicoursi** [comment]
can you please rebase and push, right now? I want to see that clean! ;)

**Comment by Porrumentzio** [comment]
Done, I think. I had problems

**Comment by nicoursi** [comment]
'git rebase --abort`

**Comment by Porrumentzio** [comment]
$ git rebase --abort
fatal: No rebase in progress?

**Comment by Porrumentzio** [comment]
We both changed the same file and lines. I have now it clear; I can commit and push

**Comment by nicoursi** [comment]
wait because you are making a mess.

**Comment by Porrumentzio** [comment]
I wait

**Comment by nicoursi** [comment]
`git rebase -i upstream esperanto2`

drop the first and the last commit. Leave the one in the middle.

ctrl+x and save
then rebase and push

**Comment by Porrumentzio** [comment]
> $ git rebase -i upstream esperanto2
> fatal: invalid upstream 'upstream'

How can I drop the commits?

**Comment by nicoursi** [comment]
`git rebase -i upstream/esperanto2`

You will have an editor. Replace the word `pick` with `d`

I asked you to google `rebase -i`. Bad student ;)

**Comment by Porrumentzio** [comment]
`-i = --interactive`,  learned! Without Google ;) 

Anyway I have the same problem as before:

> 
> $ git rebase -i upstream/esperanto2
> error: cannot rebase: You have unstaged changes.
> error: Please commit or stash them.

**Comment by nicoursi** [comment]
```
git status
git checkout -- file_to_unstage
```

**Comment by nicoursi** [comment]
>-i = --interactive
knowing the meaning of i without knowing how to use it and what's for, it is useless ;)

**Comment by Porrumentzio** [comment]
I pushed the changes. Say when it's done and I'll continue working.

**Comment by Porrumentzio** [comment]
Is it done?

**Comment by nicoursi** [comment]
yes

**Pull request merged**
