### PR TITLE
Changed icon and flags

### PR DESCRIPTION
**Pull request by Porrumentzio**
Also I added non diacritics but not esperantoish characters on `ext.dictionaryInputAdditionalInnerCharacters`

Now what remains is the script to clean the merged wordlist. I'll try tomorrow, but if you want to participate, you're completely welcome!

### CODE REVIEW

**Review by nicoursi — COMMENTED** [review]
What's the reason for adding 10% here when every key already has it?

**Comment by Porrumentzio** [comment]
No, that bepo layout is with keyWidth="9.09%p", so the bottom row gets too tiny. Having the bottom row with 10, and especial keys with 20, gets 100 (20+10*6+20).

**Comment by nicoursi** [comment]
This is the code before you modified it. No need to add one more 10%, it already works.
```   
<Row>
        <Key android:codes="-1" android:keyWidth="20%p" 
                android:isModifier="true" android:isSticky="true" android:keyEdgeFlags="left"/> 
        <Key android:codes="293" android:keyLabel="ĥ" android:keyWidth="10%p"/>
        <Key android:codes="107" android:keyLabel="k" android:keyWidth="10%p"/>
        <Key android:codes="349" android:keyLabel="ŝ" android:keyWidth="10%p" android:popupCharacters="qɵ"/>
        <Key android:codes="103" android:keyLabel="g" android:keyWidth="10%p" android:popupCharacters="ŋ"/>
        <Key android:codes="104" android:keyLabel="h" android:keyWidth="10%p" android:popupCharacters="ĥħ"/>
        <Key android:codes="102" android:keyLabel="f" android:keyWidth="10%p" android:popupCharacters="\u200b"/> <!-- This character (\u200b) is zero-width space, which we named in esperanto "falsa spaco": https://en.wikipedia.org/wiki/Zero-width_space -->
        <Key android:keyWidth="20%p" android:codes="-5" android:keyEdgeFlags="right" android:isRepeatable="true"/> 
    </Row>
```

**Comment by Porrumentzio** [comment]
It works, but the bottom row results weird. Look at the width parameter on top of block:


> <Keyboard xmlns:android="http://schemas.android.com/apk/res/android"
>     **android:keyWidth="9.09%p"**\>
>     
>     <Row>
>         
> 		<Key android:codes="98" android:keyLabel="b" android:keyEdgeFlags="left"/>
>         <Key android:codes="309" android:keyLabel="ĵ"/>
>         <Key android:codes="112" android:keyLabel="p" android:popupCharacters="þ"/>
>         <Key android:codes="111" android:keyLabel="o" android:popupCharacters="õøòóöœô"/>
>         <Key android:codes="285" android:keyLabel="ĝ" android:popupCharacters="wŵʒ"/>
>         <Key android:codes="118" android:keyLabel="v"/>
>         <Key android:codes="100" android:keyLabel="d" android:popupCharacters="ð"/>
>         <Key android:codes="108" android:keyLabel="l" android:popupCharacters="łŀ"/> 
>         <Key android:codes="106" android:keyLabel="j"/>
>         <Key android:codes="122" android:keyLabel="z" android:popupCharacters="ž"/>
>         <Key android:codes="365" android:keyLabel="ŭ" android:popupCharacters="yý" android:keyEdgeFlags="right"/>
>     </Row>
>      
>     <Row>
>         <Key android:codes="97" android:keyLabel="a" android:popupCharacters="áàâæąäãåăəāª" android:keyEdgeFlags="left"/>
>         <Key android:codes="117" android:keyLabel="u" android:popupCharacters="úùüûũů" />
>         <Key android:codes="105" android:keyLabel="i" android:popupCharacters="îï" />
>         <Key android:codes="101" android:keyLabel="e" android:popupCharacters="éèêëėě"/>
>         <Key android:codes="99" android:keyLabel="c" android:popupCharacters="çč"/>
>         <Key android:codes="116" android:keyLabel="t" android:popupCharacters="ŧ"/>
>         <Key android:codes="115" android:keyLabel="s" android:popupCharacters="ßš"/>
>         <Key android:codes="114" android:keyLabel="r" android:popupCharacters="řŕ" />
>         <Key android:codes="110" android:keyLabel="n" android:popupCharacters="ñńň"/>
>         <Key android:codes="109" android:keyLabel="m" android:popupCharacters="µ"/>
>         <Key android:codes="265" android:keyLabel="ĉ" android:popupCharacters="x" android:keyEdgeFlags="right"/>
>     </Row>
>     
>     <Row android:keyWidth="10%p">
>         <Key android:codes="-1" android:keyWidth="20%p" 
>                 android:isModifier="true" android:isSticky="true" android:keyEdgeFlags="left"/> 
>         <Key android:codes="293" android:keyLabel="ĥ" android:keyWidth="10%p"/>
>         <Key android:codes="107" android:keyLabel="k" android:keyWidth="10%p"/>
>         <Key android:codes="349" android:keyLabel="ŝ" android:keyWidth="10%p" android:popupCharacters="qɵ"/>
>         <Key android:codes="103" android:keyLabel="g" android:keyWidth="10%p" android:popupCharacters="ŋ"/>
>         <Key android:codes="104" android:keyLabel="h" android:keyWidth="10%p" android:popupCharacters="ĥħ"/>
>         <Key android:codes="102" android:keyLabel="f" android:keyWidth="10%p" android:popupCharacters="\u200b"/> 
>         <Key android:keyWidth="20%p" android:codes="-5" android:keyEdgeFlags="right" android:isRepeatable="true"/> 
>     </Row>
> </Keyboard>

All between `<Keyboard>` and `</Keyboard>` is 9.09%p, so the bottom row, due to the number of keys it have (8), gets better with 10 and 20 widths.

The reason of having 9.09 for general is that top and middle rows have 11 keys (so 100/11=9.090909...).

**Comment by nicoursi** [comment]
I still do not get it. Are you sure you are not referring to some old code, just before I committed?

In what way does this layout look weird?

IMG_20200831_222601

**Comment by Porrumentzio** [comment]
I think you have the package with the new code. Before it was this way:
irudia

I would say that in the image you posted, the bottom row has 10%p. See the bottom-bottom row, the external to package. It is always 10%p and your `Ĥ` key matches perfectly with the `,`, unlike the image I posted, where the difference can be seen.

Try by yourself changing the width of the bottom row on bepo and testing it, but I'm sure about what I said.

**Comment by Porrumentzio** [comment]
I have made a commit removing the `keyWidth` in each `<key/>`, and leaving only that on `<Row>`.
It will go with the next PR.

I'll try the python script tomorrow.

Great thanks for helping and teaching. Good night!

**Comment by nicoursi** [comment]
probably your phone is handling it differently. It does not make any sense, because every key is already manually set at 10%,  + 40% for the side keys. No need to repeat it for the whole row. I'll remove it,  you will rebase, and you will test it again and send an up to date screenshot.

**Comment by nicoursi** [comment]
before applying your change I want to make sure it really does not work, because it does work on my end.

**Comment by nicoursi** [comment]
The words_merged file  I posted for you has changed, as we edited build.gradle.

To get the up to date file you have to run: `./gradlew :addons:languages:esperanto:pack:makeDictionary`
and then you'll find the files in `addons/languages/esperanto/pack/build/dictionary`

**Comment by nicoursi** [comment]
The picture you posted belongs to a very old version. It still says "esperanto" on the space bar. Don't drive me crazy :D I fixed that gap before you put your hands on an already fixed code.

**Comment by Porrumentzio** [comment]
Hi again! I'll take a look now to the changes.
Also I think that although we were talking about different versions, one doubt I had still remains: isn't more efficient having only one `10%p` on `<Row>` than 10 `10%p` on each key?

About the dictionary, I'll add two more characters to the possible ones: `'` and `-`. I saw they are missing and splitting words, because they are sometimes used in formal Esperanto.

**Comment by nicoursi** [comment]
> Also I think that although we were talking about different versions, one doubt I had still remains: isn't more efficient having only one 10%p on <Row> than 10 10%p on each key?

It's not about efficiency. It does not affect efficiency, but the code is clearer and easier to modify with row width, instead of key width. So, if it works you can change it that way.

Alternatively,  if it does not work, you can also remove the keyboard width and apply the correct one to each row, as not all rows have the same number of keys. It would make more sense

Remember not to use TAB in XML config files, otherwise the  unit tests will fail.

I used the other method, because I didn't notice the 9.09 keyboard wise, because of that huge commenting block.

**Comment by Porrumentzio** [comment]
No matter, I'm working on it. I'm doing a new PR

**Pull request merged**
